/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MainGUI;

import Models.Sofa;
import java.awt.Desktop;
import java.io.File;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.Comparator;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Emilio
 */
public class SSInfo extends javax.swing.JFrame
{

    private ArrayList<Sofa> sofaList = new ArrayList<>(); // Array to store sofa details
    private int sofaCount = 0;  //Track the number of sofas added    
    DefaultTableModel TableModel;

    public SSInfo()
    {
        initComponents();

        String[] columns =
        {
            "Sofa ID", "Category", "Sofa Name", "Color", "Price"
        };

        TableModel = new DefaultTableModel(columns, 0);

        preloadSofas();
        updateTable();

        tblSofaDetails.setModel(TableModel);
        buttonGroup1.add(rbBlueColor);
        buttonGroup1.add(rbRedColor);
        buttonGroup1.add(rbYellowColor);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtSofaId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtSofaName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        rbBlueColor = new javax.swing.JRadioButton();
        rbRedColor = new javax.swing.JRadioButton();
        rbYellowColor = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        txtPriice = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cbCategory = new javax.swing.JComboBox<>();
        btnAdd = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSofaDetails = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        txtSearchByPrice = new javax.swing.JTextField();
        btnSearchByPrice = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        cbSearchCategory = new javax.swing.JComboBox<>();
        btnSearchByCategory = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MenuItemOPenFile = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        MenuItemExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SSIS");

        jPanel1.setBackground(new java.awt.Color(51, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 5, true));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 50)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Sofa Shop Information System.");

        jSeparator1.setBackground(new java.awt.Color(255, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(255, 0, 0));
        jSeparator1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 5, true));

        jPanel3.setBackground(new java.awt.Color(51, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 5, true), "Add a New Sofa.", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 24), new java.awt.Color(255, 0, 0)), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 51, 51))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Sofa Id:");

        txtSofaId.setBackground(new java.awt.Color(0, 255, 255));
        txtSofaId.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        txtSofaId.setForeground(new java.awt.Color(255, 0, 0));
        txtSofaId.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtSofaIdActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Sofa Name:");

        txtSofaName.setBackground(new java.awt.Color(0, 255, 255));
        txtSofaName.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        txtSofaName.setForeground(new java.awt.Color(255, 0, 0));
        txtSofaName.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtSofaNameActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("Colour:");

        rbBlueColor.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        rbBlueColor.setForeground(new java.awt.Color(255, 0, 0));
        rbBlueColor.setText("Blue");

        rbRedColor.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        rbRedColor.setForeground(new java.awt.Color(255, 0, 0));
        rbRedColor.setText("Red");
        rbRedColor.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                rbRedColorActionPerformed(evt);
            }
        });

        rbYellowColor.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        rbYellowColor.setForeground(new java.awt.Color(255, 0, 0));
        rbYellowColor.setText("Yellow");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("Price:");

        txtPriice.setBackground(new java.awt.Color(0, 255, 255));
        txtPriice.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        txtPriice.setForeground(new java.awt.Color(255, 0, 0));
        txtPriice.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtPriiceActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("Category:");

        cbCategory.setBackground(new java.awt.Color(0, 255, 255));
        cbCategory.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        cbCategory.setForeground(new java.awt.Color(255, 0, 0));
        cbCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Armchair Sofa", "Loveseat Sofa", "Sofa Bed", "Seater Sofa", "Modular Sofa", " " }));

        btnAdd.setBackground(new java.awt.Color(0, 255, 255));
        btnAdd.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 0, 0));
        btnAdd.setText("Add Sofa.");
        btnAdd.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnAddActionPerformed(evt);
            }
        });

        btnClear.setBackground(new java.awt.Color(0, 255, 255));
        btnClear.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        btnClear.setForeground(new java.awt.Color(255, 0, 0));
        btnClear.setText("Clear.");
        btnClear.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(rbRedColor)
                                .addGap(20, 20, 20)
                                .addComponent(rbBlueColor)
                                .addGap(18, 18, 18)
                                .addComponent(rbYellowColor))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtSofaName, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cbCategory, javax.swing.GroupLayout.Alignment.LEADING, 0, 277, Short.MAX_VALUE)
                                .addComponent(txtSofaId, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(txtPriice, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(btnAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSofaId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtSofaName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(rbRedColor)
                    .addComponent(rbBlueColor)
                    .addComponent(rbYellowColor))
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtPriice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnClear))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(0, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 6, true), "Sofa Details.", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 24), new java.awt.Color(255, 0, 0))); // NOI18N

        tblSofaDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String []
            {
                "Sofa Id", "Category", "Sofa Name", "Colour", "Price"
            }
        ));
        jScrollPane1.setViewportView(tblSofaDetails);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(0, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 5, true), "Searchs Sofas.", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 24), new java.awt.Color(255, 0, 0))); // NOI18N

        jPanel6.setBackground(new java.awt.Color(0, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 5, true), "Searchs by Price.", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 24), new java.awt.Color(255, 0, 0))); // NOI18N

        txtSearchByPrice.setBackground(new java.awt.Color(0, 255, 255));
        txtSearchByPrice.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        txtSearchByPrice.setForeground(new java.awt.Color(255, 0, 0));
        txtSearchByPrice.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtSearchByPriceActionPerformed(evt);
            }
        });

        btnSearchByPrice.setBackground(new java.awt.Color(0, 255, 255));
        btnSearchByPrice.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        btnSearchByPrice.setForeground(new java.awt.Color(255, 0, 0));
        btnSearchByPrice.setText("Search.");
        btnSearchByPrice.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnSearchByPriceActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("Price:");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSearchByPrice)
                    .addComponent(jLabel7)
                    .addComponent(txtSearchByPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(txtSearchByPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnSearchByPrice)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(0, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 5, true), "Searchs by Category.", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 24), new java.awt.Color(255, 0, 0))); // NOI18N

        cbSearchCategory.setBackground(new java.awt.Color(0, 255, 255));
        cbSearchCategory.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        cbSearchCategory.setForeground(new java.awt.Color(255, 0, 0));
        cbSearchCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Armchair Sofa", "Loveseat Sofa", "Sofa Bed", "Seater Sofa", "Modular Sofa", " " }));

        btnSearchByCategory.setBackground(new java.awt.Color(0, 255, 255));
        btnSearchByCategory.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        btnSearchByCategory.setForeground(new java.awt.Color(255, 0, 0));
        btnSearchByCategory.setText("Available Sofa.");
        btnSearchByCategory.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnSearchByCategoryActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("Category:");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(84, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSearchByCategory)
                    .addComponent(jLabel8)
                    .addComponent(cbSearchCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(cbSearchCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnSearchByCategory)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(264, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 686, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(10, 10, 10)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(488, 488, 488)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jMenu1.setText("File");

        MenuItemOPenFile.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MenuItemOPenFile.setText("Open File");
        MenuItemOPenFile.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                MenuItemOPenFileActionPerformed(evt);
            }
        });
        jMenu1.add(MenuItemOPenFile);
        jMenu1.add(jSeparator2);

        MenuItemExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MenuItemExit.setText("Exit");
        MenuItemExit.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                MenuItemExitActionPerformed(evt);
            }
        });
        jMenu1.add(MenuItemExit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSofaIdActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtSofaIdActionPerformed
    {//GEN-HEADEREND:event_txtSofaIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSofaIdActionPerformed

    private void txtSofaNameActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtSofaNameActionPerformed
    {//GEN-HEADEREND:event_txtSofaNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSofaNameActionPerformed

    private void rbRedColorActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_rbRedColorActionPerformed
    {//GEN-HEADEREND:event_rbRedColorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbRedColorActionPerformed

    private void txtPriiceActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtPriiceActionPerformed
    {//GEN-HEADEREND:event_txtPriiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPriiceActionPerformed

    // Tab le for sofa Details:

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnAddActionPerformed
    {//GEN-HEADEREND:event_btnAddActionPerformed
        addNewSofa();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnClearActionPerformed
    {//GEN-HEADEREND:event_btnClearActionPerformed
        clearFileds();
    }//GEN-LAST:event_btnClearActionPerformed

    private void MenuItemExitActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_MenuItemExitActionPerformed
    {//GEN-HEADEREND:event_MenuItemExitActionPerformed
        this.dispose();
    }//GEN-LAST:event_MenuItemExitActionPerformed

    // Method to search for a sofa by proce using Binary Search.
    private void btnSearchByPriceActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnSearchByPriceActionPerformed
    {//GEN-HEADEREND:event_btnSearchByPriceActionPerformed
        if (txtSearchByPrice.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Please enter a Price");
            return;
        }

        double targetPrice = Double.parseDouble(txtSearchByPrice.getText().trim());
        Collections.sort(sofaList, Comparator.comparingDouble(Sofa::getPrice)); // Sort list by Price

        int low = 0;
        int high = sofaList.size() - 1;
        while (low <= high)
        {
            int mid = (low + high) / 2;
            Sofa midSofa = sofaList.get(mid);

            if (midSofa.getPrice() == targetPrice)
            {
                JOptionPane.showMessageDialog(null, "Found: " + midSofa.getCategory() + "  - " + midSofa.getSofaName());
                return;
            }
            else if (midSofa.getPrice() < targetPrice)
            {
                low = mid + 1;
            }
            else
            {
                high = mid - 1;
            }
        }

        JOptionPane.showMessageDialog(null, "No sofa found with that Price.");

    }//GEN-LAST:event_btnSearchByPriceActionPerformed

    private void txtSearchByPriceActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtSearchByPriceActionPerformed
    {//GEN-HEADEREND:event_txtSearchByPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchByPriceActionPerformed

    private void btnSearchByCategoryActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnSearchByCategoryActionPerformed
    {//GEN-HEADEREND:event_btnSearchByCategoryActionPerformed
        // Metho to search for sofas by category
        String category = cbSearchCategory.getSelectedItem().toString();
        ArrayList<String> foundSofas = new ArrayList<>();

        for (Sofa sofa : sofaList)
        {
            if (sofa.getCategory().equals(category))
            {
                foundSofas.add(sofa.getSofaName());
            }
        }

        if (foundSofas.isEmpty())
        {
            JOptionPane.showMessageDialog(null, "No sofas available in this Category.");
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Available sofas in " + category + " : " + String.join(", ", foundSofas));

        }


    }//GEN-LAST:event_btnSearchByCategoryActionPerformed

    private void MenuItemOPenFileActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_MenuItemOPenFileActionPerformed
    {//GEN-HEADEREND:event_MenuItemOPenFileActionPerformed
        try
        {

            File archivo = new File("C:\\Users\\Emilio\\Documents\\GitHub\\CS5054AdvancedProgrammingandTechnologiesSpring2024-25\\SSIS\\sofas.csv");
//            //File archivo = new File("C:\\\\Test\\\\emilioAtenas.jpg");
//            
            if (archivo.exists())
            {
                Desktop.getDesktop().open(archivo);
            }
            else
            {
                System.out.println("El archivo no existe.");
            }

//            Runtime.getRuntime().exec("rundll32 url.dll,  FileProtocolHandler" + "C:\\Test\\emilioAtenas.jpg");
//            
//            JOptionPane.showMessageDialog(null, "The file  was open successfully!");
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_MenuItemOPenFileActionPerformed

    // Add a new sofa tot he table
    private void addNewSofa()
    {
        try
        {
            String sofaID = txtSofaId.getText().trim();
            String sofaName = txtSofaName.getText().trim();
            String category = cbCategory.getSelectedItem().toString();
            String color = getSelectedColor().trim();
            double price = Double.parseDouble(txtPriice.getText());

            // Validate inputs
            if (sofaID.isEmpty() || sofaName.isEmpty() || color.isEmpty() || price <= 0)
            {
                JOptionPane.showMessageDialog(null, "Please fill in all fields correctly.");
                return;
            }

            // Validate numeric price
            try
            {
                price = Double.parseDouble(txtPriice.getText().trim());
                if (price <= 0)
                {
                    JOptionPane.showMessageDialog(null, "Price must be greater than zero..");
                    return;

                }
            }
            catch (NumberFormatException e)
            {
                JOptionPane.showMessageDialog(null, "Invalid price format. Enter a numeric value.");

            }

            // Create new sofa object
            Sofa newSofa = new Sofa(sofaID, category, sofaName, color, price);
            sofaList.add(newSofa); // Add to ArrayList

            //Add sofa to the table
            TableModel.addRow(new Object[]
            {
                newSofa.getSofaID(), newSofa.getCategory(), newSofa.getSofaName(), newSofa.getColor(), newSofa.getPrice()
            });

            JOptionPane.showMessageDialog(null, "New sofa added successfully.");

            // Clear input fields
            clearFileds();

            // Clear input fields
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, "An Error ocurred while adding the sofa.");
        }
    }

    // Methos to Get the selected color from the radio buttons
    private String getSelectedColor()
    {
        if (rbRedColor.isSelected())
        {
            return "Red";
        }
        else if (rbBlueColor.isSelected())
        {
            return "Blue";
        }
        else if (rbYellowColor.isSelected())
        {
            return "Yellow";
        }
        else
        {
            return " ";
        }
    }

    private void clearFileds()
    {
        txtPriice.setText("");
        txtSofaId.setText("");
        txtSofaName.setText("");
        txtSearchByPrice.setText("");
        buttonGroup1.clearSelection();
        cbCategory.setSelectedIndex(0);
        cbSearchCategory.setSelectedItem(0);
    }

    // Preload sofa Data
    private void preloadSofas()
    {
        sofaList.add(new Sofa("S01", "Armchair Sofa", "High Back", "Red", 250.0));
        sofaList.add(new Sofa("S02", "Armchair Sofa", "Wingback", "Blue", 300.0));

        sofaList.add(new Sofa("S03", "Loveseat Sofa", "Modern Loveseat", "Yellow", 400.0));
        sofaList.add(new Sofa("S04", "Loveseat Sofa", "Classic Loveseat", "Red", 350.0));

        sofaList.add(new Sofa("S05", "Sofa Bed", "Folding Bed", "Blue", 500.0));
        sofaList.add(new Sofa("S06", "Sofa Bed", "Pull-out Bed", "Yellow", 600.0));

        sofaList.add(new Sofa("S07", "Seater Sofa", "Leather Recliner", "Red", 700.0));
        sofaList.add(new Sofa("S08", "Seater Sofa", "Fabric Recliner", "Blue", 750.0));

        sofaList.add(new Sofa("S09", "Modular Sofa", "L-Shaped", "Yellow", 900.0));
        sofaList.add(new Sofa("S10", "Modular Sofa", "U-Shaped", "Red", 950.0));
        sofaList.add(new Sofa("S11", "Recliner Sofa", "Classic Recliner", "Red", 700.0));
    }

    // Update Table with data from the Arraylist
    private void updateTable()
    {
        TableModel.setRowCount(0);
        for (Sofa sofa : sofaList)
        {
            TableModel.addRow(new Object[]
            {
                sofa.getSofaID(), sofa.getCategory(), sofa.getSofaName(), sofa.getColor(), sofa.getPrice()
            });
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(SSInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(SSInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(SSInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(SSInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                SSInfo sInfo = new SSInfo();
                sInfo.setVisible(true);
                sInfo.setLocationRelativeTo(null);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuItemExit;
    private javax.swing.JMenuItem MenuItemOPenFile;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnSearchByCategory;
    private javax.swing.JButton btnSearchByPrice;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbCategory;
    private javax.swing.JComboBox<String> cbSearchCategory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JRadioButton rbBlueColor;
    private javax.swing.JRadioButton rbRedColor;
    private javax.swing.JRadioButton rbYellowColor;
    private javax.swing.JTable tblSofaDetails;
    private javax.swing.JTextField txtPriice;
    private javax.swing.JTextField txtSearchByPrice;
    private javax.swing.JTextField txtSofaId;
    private javax.swing.JTextField txtSofaName;
    // End of variables declaration//GEN-END:variables

}
